spring:
  profiles:
    active: dev

---
server:
  port: 8021
spring:
  profiles: test
  application:
    name: microservicecloud-config-client-test
eureka:
  client:
    service-url:
      defaultZone: http://eureka-test.com

---
server:
  port: 8022
spring:
  profiles: dev
  application:
    name: microservicecloud-config-client-dev
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com
